UniversalAdcom/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;
using PagedList;
using UniversalAdcom.Models;
using System.Net;
using UniversalAdcom;

namespace UniversalAdcom.Controllers
{
    public class AdminController : Controller
    {
        private ApplicationUserManager _userManager;
        private ApplicationRoleManager _roleManager;

        // Controllers

        // GET: /Admin/
      //  [Authorize(Roles = "Admin")]
        #region public ActionResult Index(string searchStringUserNameOrEmail)
        public ActionResult Index(string searchStringUserNameOrEmail, string currentFilter, int? page, RegisterViewModel model)
        {
            try
            {
                int intPage = 1;
                int intPageSize = 5;
                int intTotalPageCount = 0;

                if (searchStringUserNameOrEmail != null)
                {
                    intPage = 1;
                }
                else
                {
                    if (currentFilter != null)
                    {
                        searchStringUserNameOrEmail = currentFilter;
                        intPage = page ?? 1;
                    }
                    else
                    {
                        searchStringUserNameOrEmail = "";
                        intPage = page ?? 1;
                    }
                }

                ViewBag.CurrentFilter = searchStringUserNameOrEmail;

                List<ExpandedUserDTO> col_UserDTO = new List<ExpandedUserDTO>();
                int intSkip = (intPage - 1) * intPageSize;

                intTotalPageCount = UserManager.Users
                    .Where(x => x.UserName.Contains(searchStringUserNameOrEmail))
                    .Count();
                //.Where(x => x.LastName.Contains(searchStringUserNameOrEmail)).Count();

                var result = UserManager.Users
                    .Where(x => x.UserName.Contains(searchStringUserNameOrEmail))
                    .OrderBy(x => x.UserName)
                    //.Where(x => x.LastName.Contains(searchStringUserNameOrEmail))
                    //.OrderBy(x => x.LastName)
                    .Skip(intSkip)
                    .Take(intPageSize)
                    .ToList();

                foreach (var item in result)
                {
                    ExpandedUserDTO objUserDTO = new ExpandedUserDTO();
                 
                    objUserDTO.UserName = item.UserName;
                    objUserDTO.Email = item.Email;
                    objUserDTO.LockoutEndDateUtc = item.LockoutEndDateUtc;

                    col_UserDTO.Add(objUserDTO);
                }

                // Set the number of pages
                var _UserDTOAsIPagedList =
                    new StaticPagedList<ExpandedUserDTO>
                    (
                        col_UserDTO, intPage, intPageSize, intTotalPageCount
                        );

                return View(_UserDTOAsIPagedList);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, "Error: " + ex);
                List<ExpandedUserDTO> col_UserDTO = new List<ExpandedUserDTO>();

                return View(col_UserDTO.ToPagedList(1, 25));
            }
        }
        #endregion

        // Users *****************************

        // GET: /Admin/Edit/Create 
      //  [Authorize(Roles = "Admin")]
        #region public ActionResult Create()
        public ActionResult Create()
        {
            ExpandedUserDTO objExpandedUserDTO = new ExpandedUserDTO();

            ViewBag.Roles = GetAllRolesAsSelectList();

            return View(objExpandedUserDTO);
        }
        #endregion

        // PUT: /Admin/Create
      //  [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        #region public ActionResult Create(ExpandedUserDTO paramExpandedUserDTO)
        public ActionResult Create(ExpandedUserDTO paramExpandedUserDTO)
        {
            try
            {
                if (paramExpandedUserDTO == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var Email = paramExpandedUserDTO.Email.Trim();
                var UserName = paramExpandedUserDTO.Email.Trim();
                var Password = paramExpandedUserDTO.Password.Trim();

                if (Email == "")
                {
                    throw new Exception("No Email");
                }

                if (Password == "")
                {
                    throw new Exception("No Password");
                }

                // UserName is LowerCase of the Email
                UserName = Email.ToLower();

                // Create user

                var objNewAdminUser = new ApplicationUser { UserName = UserName, Email = Email };
                var AdminUserCreateResult = UserManager.Create(objNewAdminUser, Password);

                if (AdminUserCreateResult.Succeeded == true)
                {
                    string strNewRole = Convert.ToString(Request.Form["Roles"]);

                    if (strNewRole != "0")
                    {
                        // Put user in role
                        UserManager.AddToRole(objNewAdminUser.Id, strNewRole);
                    }

                    return Redirect("~/Admin");
                }
                else
                {
                    ViewBag.Roles = GetAllRolesAsSelectList();
                    ModelState.AddModelError(string.Empty,
                        "Error: Failed to create the user. Check password requirements.");
                    return View(paramExpandedUserDTO);
                }
            }
            catch (Exception ex)
            {
                ViewBag.Roles = GetAllRolesAsSelectList();
                ModelState.AddModelError(string.Empty, "Error: " + ex);
                return View("Create");
            }
        }
        #endregion

        // GET: /Admin/Edit/TestUser 
      //  [Authorize(Roles = "Admin")]
        #region public ActionResult EditUser(string UserName)
        public ActionResult EditUser(string UserName)
        {
            if (UserName == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExpandedUserDTO objExpandedUserDTO = GetUser(UserName);
            if (objExpandedUserDTO == null)
            {
                return HttpNotFound();
            }
            return View(objExpandedUserDTO);
        }
        #endregion

        // PUT: /Admin/EditUser
      //  [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        #region public ActionResult EditUser(ExpandedUserDTO paramExpandedUserDTO)
        public ActionResult EditUser(ExpandedUserDTO paramExpandedUserDTO)
        {
            try
            {
                if (paramExpandedUserDTO == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                ExpandedUserDTO objExpandedUserDTO = UpdateDTOUser(paramExpandedUserDTO);

                if (objExpandedUserDTO == null)
                {
                    return HttpNotFound();
                }

                return Redirect("~/Admin");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, "Error: " + ex);
                return View("EditUser", GetUser(paramExpandedUserDTO.UserName));
            }
        }
        #endregion

        // DELETE: /Admin/DeleteUser
      //  [Authorize(Roles = "Admin")]
        #region public ActionResult DeleteUser(string UserName)
        public ActionResult DeleteUser(string UserName)
        {
            try
            {
                if (UserName == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                if (UserName.ToLower() == this.User.Identity.Name.ToLower())
                {
                    ModelState.AddModelError(
                        string.Empty, "Error: Cannot delete the current user");

                    return View("EditUser");
                }

                ExpandedUserDTO objExpandedUserDTO = GetUser(UserName);

                if (objExpandedUserDTO == null)
                {
                    return HttpNotFound();
                }
                else
                {
                    DeleteUser(objExpandedUserDTO);
                }

                return Redirect("~/Admin");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, "Error: " + ex);
                return View("EditUser", GetUser(UserName));
            }
        }
        #endregion

        // GET: /Admin/EditRoles/TestUser 
      //  [Authorize(Roles = "Admin")]
        #region ActionResult EditRoles(string UserName)
        public ActionResult EditRoles(string UserName)
        {
            if (UserName == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            UserName = UserName.ToLower();

            // Check that we have an actual user
            ExpandedUserDTO objExpandedUserDTO = GetUser(UserName);

            if (objExpandedUserDTO == null)
            {
                return HttpNotFound();
            }

            UserAndRolesDTO objUserAndRolesDTO =
                GetUserAndRoles(UserName);

            return View(objUserAndRolesDTO);
        }
        #endregion

        // PUT: /Admin/EditRoles/TestUser 
      //  [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]

UniversalAdcom/Views/Admin/AddRole.cshtml
@model UniversalAdcom.Models.RoleDTO

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="m-top-50">
    <div class="row">
        <div class="col-md-4 col-md-offset-2">
            <div class="row admin">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Create Role</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.RoleName,
                                       htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.RoleName,
                                           new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.RoleName,
                                           "",
                                           new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Save" class="btn btn-default" />
                                @Html.ActionLink("Back to List",
                                           "ViewAllRoles",
                                           null,
                                           new { @class = "btn btn-default" })
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</section>

UniversalAdcom/Views/Admin/Create.cshtml
@model UniversalAdcom.Models.ExpandedUserDTO
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<section class="m-top-50">
    <div class="row">
        <div class="col-md-4 col-md-offset-2">
            <div class="row admin">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Create User</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="form-group">
                            @Html.LabelFor(model => model.Email,
                                            htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Email,
                                                new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Email, "",
                                                new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Password,
                                            htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.PasswordFor(model => model.Password,
                                                new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Password,
                                                "",
                                                new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Roles,
                                            htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("Roles")
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Save" class="btn btn-default" />
                                @Html.ActionLink("Back to List",
                                                "Index",
                                                null,
                                                new { @class = "btn btn-default" })
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</section>

UniversalAdcom/Views/Admin/EditRoles.cshtml
@model UniversalAdcom.Models.UserAndRolesDTO
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<section class="m-top-50">
    <div class="row">
        <div class="col-md-4 col-md-offset-2">
            <div class="row admin">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    <br />
                    @Html.ValidationSummary(true,
                               "",
                               new { @class = "text-danger" })
                    <div>
                        @Html.ActionLink("Back",
                                   "EditUser",
                                   new { UserName = Model.UserName },
                                   new { @class = "btn btn-default" })
                        <input type="submit" value="Add Role" class="btn btn-default" />
                        @Html.DropDownList("AddRole")
                    </div>
                    <br />

                    <table class="table">
                        <tr>
                            <th>
                                Existing Roles:
                            </th>
                            <th></th>
                        </tr>

                        @foreach (var item in Model.colUserRoleDTO)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.RoleName)
                                </td>
                                <td>
                                    @if (!((Model.UserName.ToLower() ==
                                this.User.Identity.Name.ToLower()) &&
                                item.RoleName == "Administrator") &&
                                item.RoleName != "No Roles Found")
                                    {
                                        @Html.ActionLink("Delete", "DeleteRole",
                                                   new { UserName = item.UserName, RoleName = item.RoleName },
                                                    new
                                                    {
                                                        onclick =
                                                    "return confirm('Are you sure you wish to delete this role?');"
                                                    })
                                    }
                                </td>
                            </tr>
                        }
                    </table>
                }
            </div>
        </div>
    </div>
</section>

UniversalAdcom/Views/Admin/EditUser.cshtml
@model UniversalAdcom.Models.ExpandedUserDTO
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="m-top-50">
    <div class="row">
        <div class="col-md-4 col-md-offset-2">
            <div class="row admin">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Edit User</h4>
                        @Html.ValidationSummary(true,
                          "",
                          new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.UserName,
                              htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DisplayFor(model => model.UserName,
                                  new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.UserName, "",
                                  new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Email,
                              htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Email,
                                  new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Email,
                                  "",
                                  new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Password,
                              htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.PasswordFor(model => model.Password,
                                  new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Password,
                                  "",
                                  new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.LockoutEndDateUtc,
                              htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DisplayFor(model => model.LockoutEndDateUtc,
                                  new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Save" class="btn btn-default" />
                                @Html.ActionLink("Edit Roles", "EditRoles",
                                  new { UserName = Model.UserName },
                                  new { @class = "btn btn-default" })
                                @Html.ActionLink("Back to List",
                                  "Index",
                                  null,
                                  new { @class = "btn btn-default" })
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</section>

UniversalAdcom/Views/Admin/Index.cshtml
@model PagedList.IPagedList<UniversalAdcom.Models.ExpandedUserDTO>
@using PagedList.Mvc;

<section class="m-top-50">
    <div class="row">
        <div class="col-md-10 center-block">
            <div class="row m-top-25 admin">
                <p>
                    @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-default" })
                    @Html.ActionLink("Edit Roles", "ViewAllRoles", null, new { @class = "btn btn-default" })
                    @Html.ActionLink("Back to Home", "../", "Home", null, new { @class = "btn btn-default" })
                </p>
                <br />
                @using (Html.BeginForm("Index", "Admin", FormMethod.Get))
                {

                    <div class="form-group">
                        Search:&nbsp; @Html.TextBox("searchStringUserNameOrEmail", ViewBag.CurrentFilter as string)

                        <input type="submit" value="Search" />
                    </div>
                }
                <br />

                <table class="table">
                    <tr>
                        <th>
                            Email
                        </th>
                        <th>
                            Locked Out
                        </th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Email)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.LockoutEndDateUtc)
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "EditUser", new { UserName = item.UserName }) |
                                @if ((item.UserName.ToLower() != this.User.Identity.Name.ToLower()))
                                {
                                    @Html.ActionLink("Delete", "DeleteUser", new { UserName = item.UserName },
                                                                                   new { onclick = "return confirm('Are you sure you wish to delete this user?');" })
                                }
                            </td>
                        </tr>
                    }


                </table>
                <br />
                Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

                @Html.PagedListPager(Model,
                                                     page => Url.Action("Index",
                                                     new
                                                     {
                                                         page,
                                                         searchStringUserNameOrEmail = ViewBag.searchStringUserNameOrEmail,
                                                         currentFilter = ViewBag.CurrentFilter
                                                     }))
            </div>
        </div>
    </div>
</section>

UniversalAdcom/Views/Admin/ViewAllRoles.cshtml
@model IEnumerable<UniversalAdcom.Models.RoleDTO>

@{
    ViewBag.Title = "View All Roles";
}

<br />
<section class="m-top-50">
    <div class="row admin">
        <div class="col-md-8 center-block">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <p>
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
                @Html.ActionLink("Add Role", "AddRole", null, new { @class = "btn btn-default" })
            </p>
            <table class="table">
                <tr>
                    <th>
                        Role
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.RoleName)
                        </td>
                        <td>
                            @if (item.RoleName.ToLower() != "administrator")
                            {
                                @Html.ActionLink("Delete", "DeleteUserRole",
                                                              new { RoleName = item.RoleName },
                                                              new
                                                              {
                                                                  onclick =
                                                              "return confirm('Are you sure you wish to delete this role?');"
                                                              })
                            }
                        </td>

                    </tr>
                }
            </table>
        </div>
    </div>
</section>