UniversalAdcom/Controllers/BlogController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using UniversalAdcom.DAL;
using UniversalAdcom.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.ServiceModel.Syndication;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace UniversalAdcom.Controllers
{
    public class BlogController : Controller
    {

        private IBlogRepository _blogRepository;
        public static List<BlogViewModel> postList = new List<BlogViewModel>();
        public static List<AllPostsViewModel> allPostsList = new List<AllPostsViewModel>();
        public static List<AllPostsViewModel> checkCatList = new List<AllPostsViewModel>();
        public static List<AllPostsViewModel> checkTagList = new List<AllPostsViewModel>();

        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;


        public BlogController()
        {
            _blogRepository = new BlogRepository(new BlogDbContext());
        }
        public BlogController(IBlogRepository blogRepository, ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            _blogRepository = blogRepository;
            UserManager = userManager;
            SignInManager = signInManager;

        }
        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }



        #region Index

        [HttpGet]
        [AllowAnonymous]
        public ActionResult Index(int? page, string sortOrder, string searchString, string[] searchCategory, string[] searchTag)
        {
            checkCatList.Clear();
            checkTagList.Clear();
            CreateCatAndTagList();


            BlogViewModel model = new BlogViewModel();
            model.CommentViewModel = CreateCommentViewModel("mainPage", sortOrder);
            model.PagedBlogViewModel = CreatePagedBlogViewModel(page, sortOrder, searchString, searchCategory, searchTag);
            return View(model);
        }

        #endregion Index

        #region Posts/AllPosts

        [ChildActionOnly]
        public ActionResult Posts()
        {
            return PartialView();
        }

        public IPagedList<BlogViewModel> CreatePagedBlogViewModel(int? page, string sortOrder, string searchString, string[] searchCategory, string[] searchTag)
        {
            postList.Clear();

            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentSearchString = searchString;
            ViewBag.CurrentSearchCategory = searchCategory;
            ViewBag.CurrentSearchTag = searchTag;
            ViewBag.DateSortParm = string.IsNullOrEmpty(sortOrder) ? "date_desc" : "";
            ViewBag.TitleSortParm = sortOrder == "Title" ? "title_desc" : "Title";


            var posts = _blogRepository.GetPosts();
            foreach (var post in posts)
            {
                var postCategories = GetPostCategories(post);
                var postTags = GetPostTags(post);
                var likes = _blogRepository.LikeDislikeCount("postlike", post.Id);
                var dislikes = _blogRepository.LikeDislikeCount("postdislike", post.Id);
                postList.Add(new BlogViewModel() { Post = post, Modified = post.Modified, Title = post.Title, ShortDescription = post.ShortDescription, PostedOn = post.PostedOn, ID = post.Id, PostLikes = likes, PostDislikes = dislikes, PostCategories = postCategories, PostTags = postTags, UrlSlug = post.UrlSeo });
            }

            if (searchString != null)
            {
                postList = postList.Where(x => x.Title.ToLower().Contains(searchString.ToLower())).ToList();
            }

            if (searchCategory != null)
            {
                List<BlogViewModel> newlist = new List<BlogViewModel>();
                foreach (var catName in searchCategory)
                {
                    foreach (var item in postList)
                    {
                        if (item.PostCategories.Where(x => x.Name == catName).Any())
                        {
                            newlist.Add(item);
                        }
                    }
                    foreach (var item in checkCatList)
                    {
                        if (item.Category.Name == catName)
                        {
                            item.Checked = true;
                        }
                    }
                }
                postList = postList.Intersect(newlist).ToList();
            }

            if (searchTag != null)
            {
                List<BlogViewModel> newlist = new List<BlogViewModel>();
                foreach (var tagName in searchTag)
                {
                    foreach (var item in postList)
                    {
                        if (item.PostTags.Where(x => x.Name == tagName).Any())
                        {
                            newlist.Add(item);
                        }
                    }
                    foreach (var item in checkTagList)
                    {
                        if (item.Tag.Name == tagName)
                        {
                            item.Checked = true;
                        }
                    }
                }
                postList = postList.Intersect(newlist).ToList();
            }

            switch (sortOrder)
            {
                case "date_desc":
                    postList = postList.OrderByDescending(x => x.PostedOn).ToList();
                    break;
                case "Title":
                    postList = postList.OrderBy(x => x.Title).ToList();
                    break;
                case "title_desc":
                    postList = postList.OrderByDescending(x => x.Title).ToList();
                    break;
                default:
                    postList = postList.OrderBy(x => x.PostedOn).ToList();
                    break;
            }

            int pageSize = 2;
            int pageNumber = (page ?? 1);
            return postList.ToPagedList(pageNumber, pageSize);
        }


        [HttpGet]
        [AllowAnonymous]
        public ActionResult AllPosts(int? page, string sortOrder, string searchString, string[] searchCategory, string[] searchTag)
        {
            allPostsList.Clear();
            checkCatList.Clear();
            checkTagList.Clear();

            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentSearchString = searchString;
            ViewBag.CurrentSearchCategory = searchCategory;
            ViewBag.CurrentSearchTag = searchTag;
            ViewBag.DateSortParm = string.IsNullOrEmpty(sortOrder) ? "date_desc" : "";
            ViewBag.TitleSortParm = sortOrder == "Title" ? "title_desc" : "Title";

            var posts = _blogRepository.GetPosts();
            foreach (var post in posts)
            {
                var postCategories = GetPostCategories(post);
                var postTags = GetPostTags(post);
                allPostsList.Add(new AllPostsViewModel() { PostId = post.Id, Date = post.PostedOn, Description = post.ShortDescription, Title = post.Title, PostCategories = postCategories, PostTags = postTags, UrlSlug = post.UrlSeo });
            }

            if (searchString != null)
            {
                allPostsList = allPostsList.Where(x => x.Title.ToLower().Contains(searchString.ToLower())).ToList();
            }

            CreateCatAndTagList();

            if (searchCategory != null)
            {
                List<AllPostsViewModel> newlist = new List<AllPostsViewModel>();
                foreach (var catName in searchCategory)
                {
                    foreach (var item in allPostsList)
                    {
                        if (item.PostCategories.Where(x => x.Name == catName).Any())
                        {
                            newlist.Add(item);
                        }
                    }
                    foreach (var item in checkCatList)
                    {
                        if (item.Category.Name == catName)
                        {
                            item.Checked = true;
                        }
                    }
                }
                allPostsList = allPostsList.Intersect(newlist).ToList();
            }

            if (searchTag != null)
            {
                List<AllPostsViewModel> newlist = new List<AllPostsViewModel>();
                foreach (var tagName in searchTag)
                {
                    foreach (var item in allPostsList)
                    {
                        if (item.PostTags.Where(x => x.Name == tagName).Any())
                        {
                            newlist.Add(item);
                        }
                    }
                    foreach (var item in checkTagList)
                    {
                        if (item.Tag.Name == tagName)
                        {
                            item.Checked = true;
                        }
                    }
                }
                allPostsList = allPostsList.Intersect(newlist).ToList();
            }

            switch (sortOrder)
            {
                case "date_desc":
                    allPostsList = allPostsList.OrderByDescending(x => x.Date).ToList();
                    break;
                case "Title":

UniversalAdcom/Views/Shared/Info.cshtml
@{
    ViewBag.Title = "Info";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

UniversalAdcom/Views/Shared/_CampaignContactPartial.cshtml
@model UniversalAdcom.Models.CampaignContact

<div class="modal fade campaign" id="campaign" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <section>
                <div class="row">
                    @using (Html.BeginForm("AboutContact", "Home", FormMethod.Post, new { id = "campaigncontact" }))
                    {
                        @Html.AntiForgeryToken();
                        <div class="col-lg-12 center-block">
                            <div class="form-horizontal">
                                <h4 class="text-center modalHeading">Congratulations!</h4>
                                <p class="first">You made a great decision and we'd be happy to send you some more information regarding our campaigns.</p>
                                <div class="form-group">
                                    <div class="col-md-12">
                                        @Html.LabelFor(m => m.FirstName, new { @class = "form-label" })
                                        @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control", required = "required" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-12">
                                        @Html.LabelFor(m => m.LastName, new { @class = "form-label" })
                                        @Html.TextBoxFor(m => m.LastName, new { @class = "form-control", required = "required" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-12">
                                        @Html.LabelFor(m => m.CountryPrefix, new { @class = "form-label" })
                                        @Html.DropDownListFor(m => m.CountryPrefix, UniversalAdcom.Models.Extensions.GetPrefixList(), new { @class = "form-control", required = "required", Value="0" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-12">
                                        @Html.LabelFor(m => m.Phone, new { @class = "form-label" })
                                        @Html.TextBoxFor(m => m.Phone, new { @class = "form-control phone", required = "required", type = "phone", id = "PhoneCampaign" })
                                        <p id="campaignPhoneStatus"></p>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-12">
                                        @Html.LabelFor(m => m.Email, new { @class = "form-label" })
                                        @Html.TextBoxFor(m => m.Email, new { @class = "form-control", required = "required", type = "email" })
                                        @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
                                        @Html.CheckBoxFor(m => m.Hidden, new { type="hidden", value = "True", id="hidden" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-2">
                                        <input type="submit" class="btn btn-default red submit" id="submit" value="Send" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </section>
        </div>
    </div>
</div>

UniversalAdcom/Views/Shared/_FreeArtworkModal.cshtml
@model UniversalAdcom.Models.FreeArtworkContact

<div class="modal fade freeartwork" id="freeartworkmodal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">            
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <div class="col-lg-10 center-block">
                    <h5 class="modal-title text-center">Get your Free <span>Ad</span> Now!</h5>
                    <p class="text-center col-lg-8 center-block">
                        We'll send you the mock up then you tell us if there's anything you'd like to change on the design; <br />
                        It's really that easy.
                    </p>
                </div>               
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("FreeArtworkContact", "Home", FormMethod.Post,  new { @id = "emailContact" }))
                {
                    @Html.AntiForgeryToken();

                    <div class="row">
                        <div class="col-lg-10 center-block">
                            <div class="form-horizontal">
                                <div class="form-group">
                                    <div class="col-md-12">
                                        @Html.LabelFor(m => m.Name, new { @class = "form-label" })
                                        @Html.TextBoxFor(m => m.Name, new { @class="form-control", required="required"})
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-12">
                                        @Html.LabelFor(m => m.Email, new { @class = "form-label" })
                                        @Html.TextBoxFor(m => m.Email, new { @class = "form-control", required = "required", type = "email" })
                                        @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })

                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-12">
                                        @Html.LabelFor(m => m.Phone, new { @class="form-label"})
                                        @Html.TextBoxFor(m => m.Phone, new { @class="form-control phone", required="required", type = "phone", id = "Phone" })
                                        <p id="spnPhoneStatus"></p>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-12">
                                        @Html.LabelFor(m => m.BusinessName, new { @class="form-label"})
                                        @Html.TextBoxFor(m => m.BusinessName, new { @class="form-control", required="required"})
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-12">
                                        @Html.LabelFor(m => m.Position, new { @class="form-label"})
                                        @Html.TextBoxFor(m => m.Position, new { @class="form-control", required="required"})
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-12">
                                        @Html.LabelFor(m => m.Website, new { @class="form-label"})
                                        @Html.TextAreaFor(m => m.Website, new { @class="form-control", type="url", required="required"})
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-4">
                                        <input type="submit" class="btn btn-default red submit" id="submit" value="Send" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                }
            </div>          
        </div>
    </div>
</div>

UniversalAdcom/Views/Shared/_Header.cshtml
<div class="navbar navbar-inverse navbar-fixed-top nav">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="nav-icon">
                <span id="iconSwitch" class="glyphicon glyphicon-plus"></span>
            </button>
            <a href="@Url.Action("Index", "Home")" class="show-for-small float-right">
                <img src="@Url.Content("~/Content/Images/Logo.png")" />
            </a>
        </div>
        <div class="container-fluid slide-container">
            <div class="row">
                <div class="col-xs-12 col-lg-10 center-block">
                    <div class="col-sm-3 col-sm-push-1 col-md-4 col-md-push-1 col-lg-4 col-lg-push-1">
                        <a href="@Url.Action("Index", "Home")" class="hide-for-small">
                            <img src="@Url.Content("~/Content/Images/Logo.png")" />
                        </a>
                    </div>
                    <div class="col-sm-9 col-sm-push-1 col-md-8 col-lg-8 col-lg-push-2">
                        <ul class="navbar-nav">
                            <li>@Html.ActionLink("How it Works", "HowItWorks", "Home")</li>
                            <li class="dropdown">
                                @Html.ActionLink("Programs", "About", "Home", null, new { @class = "dropdown-toggle" })
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                    <li>@Html.ActionLink("County", "County", "Home")</li>
                                    <li>@Html.ActionLink("Pizza", "Pizza", "Home")</li>
                                    <li>@Html.ActionLink("Schools", "Schools", "Home")</li>
                                    <li>@Html.ActionLink("Entertainment", "Entertainment", "Home")</li>
                                </ul>
                            </li>
                            <li class="show-for-small">@Html.ActionLink("County", "County", "Home")</li>
                            <li class="show-for-small">@Html.ActionLink("Pizza", "Pizza", "Home")</li>
                            <li class="show-for-small">@Html.ActionLink("Schools", "Schools", "Home")</li>
                            <li class="show-for-small">@Html.ActionLink("Entertainment", "Entertainment", "Home")</li>
                            <li>@Html.ActionLink("Products", "Products", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                            <li>@Html.ActionLink("Media", "Index", "Blog")</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@Html.Partial("_LoginPartial")

UniversalAdcom/Views/Shared/_HowCanWeHelpModal.cshtml
@model UniversalAdcom.Models.HowCanWeHelpYou

<section class="howcanwehelpmodal">
    <div class="modal fade" id="howcanwehelp" data-attribute="howcanwehelp" role="dialog" tabindex="1">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="row">
                    <div class="col-md-12 center-block">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title text-center red">How Can We Help?</h4>
                            <p class="text-center">We're ready to answer any questions you may have!</p>
                            <p class="text-center"><small>Our customer service team is standing by to help you with whatever you may need.</small></p>
                        </div>
                        <div class="modal-body">
                            @using (@Html.BeginForm("HowCanWeHelp", "Home", FormMethod.Post, new { @id = "howcanwehelpform" }))
                            {
                                @Html.AntiForgeryToken()
                                <div class="form-horizontal">
                                    <div class="form-group">
                                        @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "Name", required = "required" })
                                    </div>
                                    <div class="form-group">
                                        @Html.DropDownListFor(m => m.CountryPrefix, UniversalAdcom.Models.Extensions.GetPrefixList(), new { @class = "form-control", required = "required", Value = "0" })
                                    </div>
                                    <div class="form-group">
                                        @Html.TextBoxFor(m => m.Phone, new { @class = "form-control", required = "required", placeholder = "Phone" })
                                    </div>
                                    <div class="form-group">
                                        @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "Email", required = "required", type = "email" })
                                    </div>
                                    <div class="form-group">
                                        <div class="col-lg-3 no-gutters">
                                            <input type="submit" value="Send" class="btn btn-default red">
                                        </div>
                                    </div>
                                </div>}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

UniversalAdcom/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <title>@ViewBag.Title - Universal AdCom</title>
    <script src="~/ckeditor/ckeditor.js"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @Html.Partial("_Header")
    <div class="container-fluid body-content">
        @RenderBody()
        <hr />
        <footer>
            <p class="text-center">&copy; @DateTime.Now.Year - Universal AdCom</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/angular")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/slick")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/Nav.js")
    @Scripts.Render("~/Scripts/EmailValidation.js")

    <!-- Go to www.addthis.com/dashboard to customize your tools -->
    <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5b155b851acd6e49"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

UniversalAdcom/Views/Shared/_ProductDescPartial.cshtml
<div class="modal fade proddesc" data-attributes="prodDesc" id="productDesc">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Product</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 product-img-container">
                        <img ng-attr-id="{{product.id}}" ng-src="{{ product.mainImg }}" class="img-responsive prodImg" />
                        @Html.Partial("_SocialMedia")
                        <div class="col-xs-3 col-sm-3 col-md-2 col-lg-2  no-gutters">
                            <img id="thumbOne" ng-src="{{product.thumb_one}}" class="img-responsive thumb" ng-click="thumbOneSwap($event)" />
                        </div>
                        <div class="col-xs-3 col-sm-3 col-md-2 col-lg-2 no-gutters"><img id="thumbTwo" ng-src="{{product.thumb_two }}" class="img-responsive thumb" ng-click="thumbOneSwap($event)" /></div>
                        <div class="col-xs-3 col-sm-3 col-md-2 col-lg-2 no-gutters"><img id="thumbThree" ng-src="{{product.print }}" class="img-responsive thumb" ng-click="thumbOneSwap($event)" /></div>
                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                        <h5>{{ product.heading }}</h5>
                        <p><b>Description:</b> <br /> {{ product.desc }}</p>                       
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

UniversalAdcom/Views/Shared/_SocialMedia.cshtml
<iframe src="https://www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.uac4u.com%2Fproducts&width=96&layout=button&action=like&size=small&show_faces=false&share=true&height=65&appId" width="96" height="65" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true" allow="encrypted-media"></iframe>

UniversalAdcom/Views/Shared/_SuccessModal.cshtml
<div class="modal fade clearSession" id="successModal" tabindex="-1" role="dialog" aria-labelledby="successModal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <div class="modal-body">
                    <h4>@ViewBag.Message!</h4>
                </div>
            </div>
        </div>
    </div>
</div>

UniversalAdcom/Views/Shared/_VideoHeader.cshtml
<section class="headerVideo container-fluid relative">
    <video autoplay loop src="@Url.Content("/Content/Video/UacBuildingVideo.mp4")" type="video/mp4"></video>
    <div class="row">
        <div class="col-xs-12 col-sm-9 col-md-9 col-lg-9 center-block">
            <h1 class="text-center font-white">The Advertising Specialists</h1>
            <div class="col-xs-10 col-sm-3 col-sm-offset-1 col-md-3 col-md-push-1 col-lg-2 col-lg-offset-2">
                <h2>YOUR NEXT RIDICULOUS <span>AD</span>VANTAGE</h2>
            </div>
            <div class="col-xs-10 col-sm-5 col-md-5 col-md-push-1 col-lg-4 easiest">
                <h5>The easiest, most effective way to build your business just got simpler.</h5>
                <div class="row">
                    <div class="col-xs-6 col-sm-6 col-md-5 col-lg-6">
                        @Html.ActionLink("Start Here", "HowItWorks", "Home", null, new { @class = "btn btn-default red" })
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-5 col-md-pull-1 col-lg-6">             
                        @Html.ActionLink("Learn More", "About", "Home", null, new { @class = "btn btn-default white" })
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 center-block">
            <ul>
                <li class="text-center">
                    <span class="chevron"></span>
                </li>
                <li class="text-center">
                    <span class="chevron"></span>
                </li>
            </ul>
        </div>
    </div>
</section>